// <auto-generated />
using System;
using ItbisDgii.Infraestructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ItbisDgii.Infraestructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ItbisDgii.Domain.Entities.ComprobanteFiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContribuyenteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Itbis18")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NCF")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("nvarchar(19)");

                    b.Property<string>("RncCedula")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ContribuyenteId");

                    b.HasIndex("RncCedula", "NCF")
                        .IsUnique();

                    b.ToTable("ComprobantesFiscales");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5d6b18c6-51e9-4a7f-aedb-6b3649abf69c"),
                            ContribuyenteId = new Guid("67dac684-bee5-4b0a-9e48-30e3f95f7471"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Itbis18 = 36.00m,
                            Monto = 200.00m,
                            NCF = "E310000000001",
                            RncCedula = "98754321012"
                        },
                        new
                        {
                            Id = new Guid("3ee9c3fa-a3f6-4a59-b5b3-dd7fc5f623ff"),
                            ContribuyenteId = new Guid("67dac684-bee5-4b0a-9e48-30e3f95f7471"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Itbis18 = 180.00m,
                            Monto = 1000.00m,
                            NCF = "E310000000002",
                            RncCedula = "98754321012"
                        },
                        new
                        {
                            Id = new Guid("aa5a5c5c-5a9a-4a7f-9d2a-6b3649abf69c"),
                            ContribuyenteId = new Guid("d991f903-4396-4aba-9fee-91fc110ab8bc"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Itbis18 = 90.00m,
                            Monto = 500.00m,
                            NCF = "E310000000003",
                            RncCedula = "123456789"
                        });
                });

            modelBuilder.Entity("ItbisDgii.Domain.Entities.Contribuyente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RncCedula")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RncCedula")
                        .IsUnique();

                    b.ToTable("Contribuyentes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("67dac684-bee5-4b0a-9e48-30e3f95f7471"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Estatus = 0,
                            Nombre = "JUAN PEREZ",
                            RncCedula = "98754321012",
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("d991f903-4396-4aba-9fee-91fc110ab8bc"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Estatus = 0,
                            Nombre = "FARMACIA TU SALUD",
                            RncCedula = "123456789",
                            Tipo = 1
                        });
                });

            modelBuilder.Entity("ItbisDgii.Domain.Entities.ComprobanteFiscal", b =>
                {
                    b.HasOne("ItbisDgii.Domain.Entities.Contribuyente", "Contribuyente")
                        .WithMany("ComprobantesFiscales")
                        .HasForeignKey("ContribuyenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contribuyente");
                });

            modelBuilder.Entity("ItbisDgii.Domain.Entities.Contribuyente", b =>
                {
                    b.Navigation("ComprobantesFiscales");
                });
#pragma warning restore 612, 618
        }
    }
}
